### PR TITLE
Switch from Godep to govendor

### PR DESCRIPTION
**Pull request by croaky**
We're seeing Godep problems on Heroku.
https://dashboard.heroku.com/apps/thoughtbot-rss/activity

govendor is worth trying to stay with the community.
https://github.com/kardianos/govendor

### CODE REVIEW

**Comment by croaky** [comment]
Ready for review @thoughtbot/go

**Comment by croaky** [comment]
I was thinking `govendor` was the new, on-track-to-be-official tool, https://github.com/golang/dep. Mixed them up. Looks like `dep` isn't supported by https://devcenter.heroku.com/articles/deploying-go yet, though.

**Comment by croaky** [comment]
I tested this from a manual deploy at https://dashboard.heroku.com/apps/thoughtbot-rss/deploy/github and was able to get it to deploy cleanly, fixing the blocked deploys with Godeps.

**Comment by odlp** [comment]
I reckon [Glide](https://github.com/Masterminds/glide) is worth considering.

- It allows [test imports to be separated](https://github.com/thoughtbot/location/blob/master/glide.lock#L38) from normal imports. Does `govendor` support this?
- Supported by the [Heroku buildpack](https://github.com/heroku/heroku-buildpack-go)
- *Relatively* painless to [setup on CI like Travis](https://github.com/thoughtbot/location/blob/master/.travis.yml#L6:L11)
- It's very bundler-esque, which could be helpful for Rubyists learning Go

**Comment by croaky** [comment]
> It allows test imports to be separated from normal imports

Yup! https://github.com/kardianos/govendor#sub-commands includes `+local` option for each command, such as `govendor test +local`

> Supported by the Heroku buildpack

govendor is as well. It also has some nice official docs at https://devcenter.heroku.com/articles/go-dependencies-via-govendor

> Relatively painless to setup on CI like Travis

Nice. govendor is also running on Circle in this PR.

> It's very bundler-esque, which could be helpful for Rubyists learning Go

That sounds like the main difference from the list so far. One question I have is whether Glide users have to maintain `glide.yaml` manually? In addition to the `import`s in files?

I'm thinking I'll keep govendor in this project for now as a comparison with the `location` project so we have a couple of projects to compare real-world experiences with.

I think it would be cool to start getting these decisions into https://github.com/thoughtbot/guides/tree/master/best-practices and https://github.com/thoughtbot/guides/tree/master/style, though, for Go, so we have some standard ways of doing things as a team. Happy to switch this project over to Glide, or dep, or whatever we decide as a standard in `guides`.

**Pull request merged**
